name: Package OpenWrt

on:
  workflow_dispatch:
    inputs:
      armvirt_url:
        description: 'OPENWRT_ARMVIRT_URL'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Package Armvirt as OpenWrt
      uses: ophub/flippy-openwrt-actions@main
      env:
        OPENWRT_ARMVIRT: ${{ github.event.inputs.armvirt_url }}
        PACKAGE_SOC: r66s
        WHOAMI: miyling
        OPENWRT_VER: R$(date +%y.%-m.%-d)
        DISTRIB_REVISION: $OPENWRT_VER By Miyling
        KERNEL_VERSION_NAME: 6.1.91_6.6.31
        KERNEL_AUTO_LATEST: false
        
    - name: Upload artifact to Actions
      uses: miyling/upload-artifact-as-is@master
      if: env.PACKAGED_STATUS == 'success' && !cancelled()
      with:
        path: ${{ env.PACKAGED_OUTPUTPATH }}/*
