name: Package OpenWrt

on:
  workflow_dispatch:
    inputs:
      armvirt_url:
        description: 'OPENWRT_ARMVIRT_URL'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Package Armvirt as OpenWrt
      if: true && !cancelled()
      uses: ophub/flippy-openwrt-actions@main
      env:
        OPENWRT_ARMVIRT: ${{ github.event.inputs.armvirt_url }}
        PACKAGE_SOC: r66s
        WHOAMI: miyling
        DISTRIB_REVISION: $(OPENWRT_VER) By Miyling
        
    - name: Upload artifact to Actions
      uses: miyling/upload-artifact-as-is@master
      if: true && !cancelled()
      with:
        path: ${{ env.PACKAGED_OUTPUTPATH }}/*
